- name: create user
  ansible.builtin.user:
    name: roboshop
- name: remove old directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: create new directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: download application
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
- name: unzipping file
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes

# - name: download application from nexus
#   ansible.builtin.get_url:
#     url: "{{NEXUS_URL}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
#     dest: /tmp
#     url_username: "admin"
#     url_password: "java"
# - name: unzipping file
#   ansible.builtin.unarchive:
#     src: "/tmp/{{component}}-{{app_version}}.zip"
#     dest: /app
#     remote_src: yes