- name: create user
  ansible.builtin.user:
    name: roboshop
- name: create directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: download application
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
- name: unzipping file
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes