- name: installing mysql
  ansible.builtin.command: dnf install mysql -y
- name: checking existing data in mysql
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema
- name: cities data
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/shipping.sql
  when: schema.stdout == "0"