- name: installing mysql
  ansible.builtin.command: dnf install mysql -y
- name: checking existing data in mysql
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema
- name: cities data
  ansible.builtin.shell: |
    mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/db/schema.sql
    mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/db/app-user.sql
    mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/db/master-data.sql
  when: schema.stdout == "0"